### ISSUE TITLE
Feature request: specify level to take a point

### ISSUE THREAD

**Issue by maximum4805** [NumyAddon/TalentTreeViewer#7]
It'd be nice to be able to specify the level a point is allocated in the tree when available. I've noticed when most addons load the talents, they allocate the points from top to bottom (they don't take capstone talents until the rest of the tree has been filled).

Icy Veins in their leveling guides (for example, [ww monk](https://www.icy-veins.com/wow/windwalker-monk-leveling-guide)) tell where to put points when leveling up.

Example:

- Lv. 10: Tiger's Lust
- Lv. 11: Fists of Fury

This is useful if leveling up a new class/spec one is not familiarized with.

Another improvement would be to automatically fill the tree after leveling up.

Just an idea :)

Thanks for the addon.

**Comment by Numynum** [comment]
related issues: https://github.com/NumyAddon/TalentLoadoutManager/issues/7 and https://github.com/NumyAddon/TalentTreeTweaks/issues/4

I've spent a few days playing around with some ideas, and have an early WIP: https://github.com/NumyAddon/TalentTreeViewer/releases/tag/v2.3.0-alpha5

todo:
- [x] check whether blizzard supports adding extra data into their loadout strings
- [x] create a format
- [x] describe the format, so that other websites / addons can use it if they want
- [x] record talent choice order
- [x] export button creates a string with the recorded leveling build
- [x] switch between recorded leveling builds
- [x] clear the recorded build, and create a new "save"
- [x] allow resuming previous recordings
- [x] allow resuming empty recordings without clearing the tree
- [x] import exported builds that include a leveling build
- [x] fix import creating multiple recorded builds
- [x] adjust the order logic, to correctly match the level at which you'd buy the talent
- [x] support importing Icy-veins talent calculator links (including from leveling guides) 
- [ ] allow the user to clear the "recorded builds" list
- [x] general cleanup
- [ ] [maybe] adjust the level slider whenever you buy a talent
- [ ] [maybe] fix UX issues when creating leveling builds that start halfway down the tree
- [ ] more probably

talent loadout manager todo:
- [x] allow saving currently selected build from TTViewer
- [x] allow importing a leveling build from an export string
- [x] allow importing a leveling build from icy-veins
- [x] allow exporting a leveling build
- [x] update the "apply loadout" logic, to follow the leveling order, rather than the current random-ish order (this would include the auto-reapply on lvl up feature, making it a truly seamless experience to follow a leveling build)
- [ ] [maybe] display the leveling order on the regular blizzard talent tree

possible feature, not sure which addon it'd best fit into
- [ ] allow recording choices on the default talent UI, instead of only on the TTViewer UI
- [ ] display leveling build when "inspecting" a talent link in the blizzard default UI

**Comment by Numynum** [comment]
https://www.curseforge.com/wow/addons/talent-loadout-manager and https://www.curseforge.com/wow/addons/talenttree-viewer now support leveling builds 🙂 
closing this issue
